---
- name: Install PHP and required modules
  ansible.builtin.apt:
    name: php
    state: present
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql
  when: ansible_os_family == 'Debian'
  notify: restart apache

- name: Check PHP processing
  ansible.builtin.command: php -v
